### PR TITLE
feat: support Bareos plugins for Filedaemon (FD)

### PR DESCRIPTION
**Pull request by adf-patrickha**
* Adds support for Bareos FD plugins ([Doc](https://docs.bareos.org/TasksAndConcepts/Plugins.html#file-daemon-plugins)) 
  * For now the functionality of MariaDB, MySQL, PostgreSQL and LDAP is added. But all require a dedicated FileSet configuration on the Bareos Director's side. 
  * The functionality to add plugins to FileSets has been added in https://github.com/adfinis/ansible-role-bareos_dir/pull/2
  * Plugins can be added for hosts or also for whole groups (for example a host group `mariadb_hosts`) on host/group vars level, by adding the list `bareos_fd_plugins`. Example:
    ```yaml
    bareos_fd_plugins:
      - mariabackup
     ``` 
    * Possible values for now are: "mariabackup", "mysql", "postgresql", "ldap".

### CODE REVIEW

**Comment by adf-patrickha** [comment]
I checked, if there needs to be a distinction between plugin package names per distro. but apparently the names seem to match.  Checked on Debian and RHEL.

**Comment by adf-patrickha** [comment]
Should be ready to add.

**Comment by fadnincx** [comment]
> I checked, if there needs to be a distinction between plugin package names per distro. but apparently the names seem to match. Checked on Debian and RHEL.

@adf-patrickha Apparently, Fedora 37 is failing because `No package bareos-filedaemon available.`. Either we fix this, or we remove support (and test) for fedora 37.

**Comment by adf-patrickha** [comment]
> > I checked, if there needs to be a distinction between plugin package names per distro. but apparently the names seem to match. Checked on Debian and RHEL.
> 
> @adf-patrickha Apparently, Fedora 37 is failing because `No package bareos-filedaemon available.`. Either we fix this, or we remove support (and test) for fedora 37.

fair point. I'll look into it why it cannot find the package. Normally the role bareos_repository should take care of this. If the package is not available upstream from Bareos for Fedora 37, I'll remove it altogether.

**Comment by fadnincx** [comment]
> OK so Bareos does not provide packages for Fedora 37 anymore in https://download.bareos.org/current/ Therefore I replaced 37 in the CI with Fedora latest (39): #2. All checks should pass now.

:+1: so maybe a quick rebase, then this PR is all good to go.

**Pull request merged**
